#version: 0.2

phases:
  build:
    command:
      - echo Build started on 'date'
      - mvn test
    
    post_build:
      - echo Build completed on 'data'
      - mvn package
artifactory:
  files:
    - target/devicefarm-0.1.0.jar

